config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  get 'posts/show'

  resources :posts do
    member do
      get :detail
    end

  end
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 def after_sign_in_path_for(resource)
       posts_show_path
 end

 private

    def sign_in_required
       redirect_to new_user_session_url unless user_signed_in?
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 before_action :sign_in_required, only: [:show]

  def index
    @posts = Post.all
  end

  def show
    @posts = Post.all
  end

  def detail
    @post = Post.find(params[:id])
  end

  def new
  end

  def create
    @post = Post.new(post_params)
    if  @post.save
      redirect_to posts_show_path
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_show_path
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_show_path
  end

  private

   def post_params
     params.require(:post).permit(:title, :body)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div id="footer_inner">
     <p>Copyright RailsCamp 2015 All Rights Reserved</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <p id="logo"><a href="">RailsCamp<span>Blog</span></a></p>
    <nav>
        <% if user_signed_in? %>
            <ul>
              <li><a><%= link_to 'トップ', posts_show_path %></a></li>
              <li><a><%= link_to '新規投稿', new_post_path %></a></li>
              <li><a><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></a></li>
              <div class="clear"></div>
            </ul>
        <% else %>
            <ul>
              <li><a><%= link_to 'トップ', root_path %></a></li>
              <li><a><%= link_to '新規登録', new_user_registration_path %></a></li>
              <li><a><%= link_to 'ログイン', new_user_session_path %></a></li>
              <div class="clear"></div>
            </ul>
        <% end %>
    </nav>
    <div class="clear"></div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KadaiApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/index.html.erb
<div id="main">
  <%= image_tag 'main-img.jpg' %>
</div>

<div id="article_wrap">
  <% @posts.each do |post| %>
  <div id="article_list">
    <div>
      <h2><%= link_to post.title, detail_post_path(post) %></h2>
      <p><%= post.created_at %></p>
    </div>
  </div>
  <% end %>
</div>


  <div id="sidebar">
   <h2>★PV数ランキング</h2>
   <ul>
      <li><a href="">記事タイトル記事タイトル１記事タイトル記事タイトル<span>（10PV）</span></a></li>
      <li><a href="">記事タイトル記事タイトル１記事タイトル記事タイトル<span>（8PV）</span></a></li>
      <li><a href="">記事タイトル記事タイトル１記事タイトル記事タイトル<span>（2PV）</span></a></li>
   </ul>
  </div>
  <div class="clear"></div>
</div>

app/views/pages/show.html.erb
<div id="main">
  <%= image_tag 'main-img.jpg' %>
</div>

<div id="article_wrap">
    <% @posts.each do |post| %>
    <div id="article_list">
      <div>
        <h2><%= link_to post.title, post_path(post) %></h2>
        <p><%= post.created_at %></p>
        <p>
          <%= link_to '編集', edit_post_path(post) %>
          <%= link_to '削除', post_path(post),
          method: :delete,
          data: { confirm: '削除してよろしいですか？'} %>
        </p>
      </div>
    </div>
    <% end %>
  </div>

app/views/posts/detail.html.erb
<div id="title">
  <div>
    <p><%= @post.created_at %> </p>
    <h1><%= @post.title %></h1>
  </div>
</div>

<div id="article_wrap">
  <div id="content">
    <div>
      <h2><%= @post.body %></h2>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<% provide(:title, 'edit')%>

<%= form_for @post, url: post_path(@post) do |f| %>

  <p><%= f.label :title, "タイトル" %></p>
  <p><%= f.text_field :title  %></p>

  <p><%= f.label :body, "記事内容" %></p>
  <p><%= f.text_field :body %></p>

  <%= f.submit "create article"  %>
<% end %>

<%= render 'layouts/footer' %>

app/views/posts/index.html.erb
<div id="main">
  <%= image_tag 'main-img.jpg' %>
</div>

<div id="article_wrap">
  <% @posts.each do |post| %>
  <div id="article_list">
    <div>
      <h2><%= link_to post.title, post_path(post) %></h2>
      <p><%= post.created_at %></p>
    </div>
  </div>
  <% end %>
</div>


  <div id="sidebar">
   <h2>★PV数ランキング</h2>
   <ul>
      <li><a href="">記事タイトル記事タイトル１記事タイトル記事タイトル<span>（10PV）</span></a></li>
      <li><a href="">記事タイトル記事タイトル１記事タイトル記事タイトル<span>（8PV）</span></a></li>
      <li><a href="">記事タイトル記事タイトル１記事タイトル記事タイトル<span>（2PV）</span></a></li>
   </ul>
  </div>
  <div class="clear"></div>
</div>

app/views/posts/new.html.erb
<% provide(:title, 'new')%>

<%= form_for :post, url: posts_path do |f| %>

  <p><%= f.label :title, "タイトル" %></p>
  <p><%= f.text_field :title  %></p>

  <p><%= f.label :body, "記事内容" %></p>
  <p><%= f.text_field :body %></p>


  <%= f.submit "create article"  %>
<% end %>

app/views/posts/show.html.erb
<div id="main">
  <%= image_tag 'main-img.jpg' %>
</div>

<div id="article_wrap">
    <% @posts.each do |post| %>
    <div id="article_list">
      <div>
        <h2><%= link_to post.title, detail_post_path(post) %></h2>
        <p><%= post.created_at %></p>
        <p>
          <%= link_to '編集', edit_post_path(post) %>
          <%= link_to '削除', post_path(post),
          method: :delete,
          data: { confirm: '削除してよろしいですか？'} %>
        </p>
      </div>
    </div>
    <% end %>
  </div>

  <div id="sidebar">
   <h2>★PV数ランキング</h2>
   <ul>
      <li><a href="">記事タイトル記事タイトル１記事タイトル記事タイトル<span>（10PV）</span></a></li>
      <li><a href="">記事タイトル記事タイトル１記事タイトル記事タイトル<span>（8PV）</span></a></li>
      <li><a href="">記事タイトル記事タイトル１記事タイトル記事タイトル<span>（2PV）</span></a></li>
   </ul>
  </div>
  <div class="clear"></div>
</div>